# Generated by Django 5.2.8 on 2026-02-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.CharField(max_length=180, unique=True)),
            ],
            options={
                'ordering': ['pasta'],
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('autor', models.CharField(blank=True, max_length=120)),
                ('tipo', models.CharField(choices=[('incidente', 'Incidente'), ('solicitacao', 'Solicitacao'), ('melhoria', 'Melhoria'), ('programado', 'Programado')], default='solicitacao', max_length=20)),
                ('urgencia', models.CharField(choices=[('normal', 'Normal'), ('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('arquivo', models.CharField(blank=True, max_length=255)),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_atendimento', 'Em atendimento'), ('fechado', 'Fechado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.CharField(blank=True, max_length=30)),
                ('nome', models.CharField(blank=True, max_length=120)),
                ('sobrenome', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('grupo', models.CharField(blank=True, max_length=120)),
                ('situacao', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('equipamento', models.CharField(blank=True, max_length=120)),
                ('documento', models.CharField(blank=True, max_length=120)),
                ('arquivo', models.CharField(blank=True, max_length=255)),
                ('situacao', models.CharField(blank=True, max_length=80)),
                ('data', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interno', models.CharField(blank=True, max_length=60)),
                ('patrimonio', models.CharField(blank=True, max_length=60)),
                ('selo_patrimonio', models.CharField(blank=True, max_length=60)),
                ('equipamento', models.CharField(max_length=120)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('marca', models.CharField(blank=True, max_length=120)),
                ('serie', models.CharField(blank=True, max_length=120)),
                ('mem', models.CharField(blank=True, max_length=40)),
                ('processador', models.CharField(blank=True, max_length=120)),
                ('geracao', models.CharField(blank=True, max_length=60)),
                ('hd', models.CharField(blank=True, max_length=80)),
                ('mod_hd', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['equipamento'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo', models.CharField(max_length=120)),
                ('data', models.DateField(blank=True, null=True)),
                ('qtd', models.CharField(blank=True, max_length=40)),
                ('nome', models.CharField(blank=True, max_length=120)),
                ('departamento', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('nome', models.CharField(blank=True, max_length=120)),
                ('fabricante', models.CharField(blank=True, max_length=120)),
                ('endereco_mac', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['ip'],
            },
        ),
        migrations.CreateModel(
            name='Ramal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.CharField(blank=True, max_length=30)),
                ('nome', models.CharField(blank=True, max_length=120)),
                ('sobrenome', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('grupo', models.CharField(blank=True, max_length=120)),
                ('situacao', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitacao', models.CharField(max_length=200)),
                ('qtd', models.CharField(blank=True, max_length=30)),
                ('valor', models.CharField(blank=True, max_length=50)),
                ('total', models.CharField(blank=True, max_length=50)),
                ('requisitado', models.DateField(blank=True, null=True)),
                ('aprovado', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao'), ('esperando', 'Esperando')], default='esperando', max_length=20)),
                ('recebido', models.DateField(blank=True, null=True)),
                ('nf', models.CharField(blank=True, max_length=80)),
                ('tipo', models.CharField(blank=True, max_length=80)),
                ('fornecedor', models.CharField(blank=True, max_length=160)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('computador', models.CharField(blank=True, max_length=120)),
                ('setor', models.CharField(blank=True, max_length=120)),
                ('serial', models.CharField(blank=True, max_length=140)),
                ('conta', models.CharField(blank=True, max_length=140)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=120)),
                ('nome_completo', models.CharField(max_length=180)),
                ('perfil', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=80)),
                ('ramal', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['nome_completo'],
            },
        ),
    ]
